# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitBump < Formula
  desc "gitcomicome"
  homepage "https://github.com/lll-lll-lll-lll/gitcomicome"
  version "0.1.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lll-lll-lll-lll/gitcomicome/releases/download/v0.1.4/git-bump_darwin_x86_64.tar.gz"
      sha256 "c9e07c349532d7d64a071e6a33e6bbc0d173597d69960854787241e1055cf19a"

      def install
        bin.install "git-bump"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lll-lll-lll-lll/gitcomicome/releases/download/v0.1.4/git-bump_darwin_arm64.tar.gz"
      sha256 "e7f674cd3a57c88dcf32c5ea89237ebad29c8cd7bf1192cb1357e705d63051ab"

      def install
        bin.install "git-bump"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lll-lll-lll-lll/gitcomicome/releases/download/v0.1.4/git-bump_linux_arm64.tar.gz"
      sha256 "f9bc7bdfcc09d6937c25482bc0dd78f10b5ee01fffeda89a8762c256bb2edc70"

      def install
        bin.install "git-bump"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lll-lll-lll-lll/gitcomicome/releases/download/v0.1.4/git-bump_linux_x86_64.tar.gz"
      sha256 "3302ab628764507551df32e581d0fc3b686596069327b7a35c14c9abf81f3fed"

      def install
        bin.install "git-bump"
      end
    end
  end

  test do
    system "#{bin}/gitcomicome --version"
  end
end
