# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitcomicome < Formula
  desc "gitcomicome"
  homepage "https://github.com/lll-lll-lll-lll/gitcomicome"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lll-lll-lll-lll/gitcomicome/releases/download/v0.1.5/gitcomicome_darwin_arm64.tar.gz"
      sha256 "50afd864fd9bebafacafea16466866b54ff26b094245e5d3476b501a710fb379"

      def install
        bin.install "gitcomicome"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lll-lll-lll-lll/gitcomicome/releases/download/v0.1.5/gitcomicome_darwin_x86_64.tar.gz"
      sha256 "b3f8eb57026b2887c8205744f3416b40be82950aff8fc59d838e4a699d06c589"

      def install
        bin.install "gitcomicome"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lll-lll-lll-lll/gitcomicome/releases/download/v0.1.5/gitcomicome_linux_x86_64.tar.gz"
      sha256 "4927e46d9bcdd2b5a7cdd4d9d338df2e774401483eb944a4e1908c9118ef9906"

      def install
        bin.install "gitcomicome"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lll-lll-lll-lll/gitcomicome/releases/download/v0.1.5/gitcomicome_linux_arm64.tar.gz"
      sha256 "6d7b83727bf1aea532068dce0872fb42034458c5cb3dc708a0bc315b57e20dca"

      def install
        bin.install "gitcomicome"
      end
    end
  end

  test do
    system "#{bin}/gitcomicome --version"
  end
end
